var perfect_pokemons = [
    {
        candy_group: "이상해씨",
        pokedex_no: "1",
        lucky: false,
        shiny: false,
        shadow: false,
        purified: false,
        region: "",
        costume: "",
        weight: "5.66",
        height: "0.74",
        knows_attack: "",
        meet: "w",
        ball: "p",
        egg_type: "",
        egg_received_date: "",
        egg_hatched_date: "",
        postcard_received_date: "",
        trade_date: "",
        caught_date: "2020-11-15",
        event: "",
    },
    {
        candy_group: "",
        pokedex_no: "3",
        lucky: true,
        shiny: false,
        shadow: false,
        purified: false,
        region: "",
        costume: "",
        weight: "88.1",
        height: "1.97",
        knows_attack: "하드플랜트",
        meet: "w",
        ball: "p",
        egg_type: "",
        egg_received_date: "",
        egg_hatched_date: "",
        postcard_received_date: "",
        trade_date: "2020-01-22",
        caught_date: "2020-01-17",
        event: "",
    },
    {
        candy_group: "",
        pokedex_no: "3",
        lucky: false,
        shiny: false,
        shadow: false,
        purified: false,
        region: "",
        costume: "",
        weight: "102.15",
        height: "2.04",
        knows_attack: "",
        meet: "w",
        ball: "h",
        egg_type: "",
        egg_received_date: "",
        egg_hatched_date: "",
        postcard_received_date: "",
        trade_date: "",
        caught_date: "2017-02-16",
        event: "",
    },
    {
        candy_group: "파이리",
        pokedex_no: "6",
        lucky: true,
        shiny: false,
        shadow: false,
        purified: false,
        region: "",
        costume: "",
        weight: "116.69",
        height: "1.81",
        knows_attack: "블라스트번",
        meet: "w",
        ball: "s",
        egg_type: "",
        egg_received_date: "",
        egg_hatched_date: "",
        postcard_received_date: "",
        trade_date: "2018-12-03",
        caught_date: "2018-12-02",
        event: "",
    },
    {
        candy_group: "",
        pokedex_no: "6",
        lucky: false,
        shiny: false,
        shadow: false,
        purified: false,
        region: "",
        costume: "",
        weight: "114.9",
        height: "1.96",
        knows_attack: "",
        meet: "w",
        ball: "h",
        egg_type: "",
        egg_received_date: "",
        egg_hatched_date: "",
        postcard_received_date: "",
        trade_date: "",
        caught_date: "2018-03-13",
        event: "",
    },
    {
        candy_group: "",
        pokedex_no: "6",
        lucky: false,
        shiny: false,
        shadow: false,
        purified: false,
        region: "",
        costume: "",
        weight: "70.91",
        height: "1.7",
        knows_attack: "용의숨결",
        meet: "w",
        ball: "h",
        egg_type: "",
        egg_received_date: "",
        egg_hatched_date: "",
        postcard_received_date: "",
        trade_date: "",
        caught_date: "2019-12-16",
        event: "",
    },
    {
        candy_group: "",
        pokedex_no: "6",
        lucky: false,
        shiny: false,
        shadow: false,
        purified: false,
        region: "",
        costume: "고깔모자",
        weight: "87.67",
        height: "1.75",
        knows_attack: "용의숨결/블라스트번",
        meet: "w",
        ball: "s",
        egg_type: "",
        egg_received_date: "",
        egg_hatched_date: "",
        postcard_received_date: "",
        trade_date: "2022-07-08",
        caught_date: "2022-01-01",
        event: "",
    },
    {
        candy_group: "꼬부기",
        pokedex_no: "9",
        lucky: false,
        shiny: false,
        shadow: false,
        purified: false,
        region: "",
        costume: "",
        weight: "96.41",
        height: "1.82",
        knows_attack: "",
        meet: "w",
        ball: "h",
        egg_type: "",
        egg_received_date: "",
        egg_hatched_date: "",
        postcard_received_date: "",
        trade_date: "",
        caught_date: "2018-03-08",
        event: "",
    },
    {
        candy_group: "꼬렛",
        pokedex_no: "19",
        lucky: true,
        shiny: false,
        shadow: false,
        purified: false,
        region: "",
        costume: "",
        weight: "2.49",
        height: "0.27",
        knows_attack: "",
        meet: "w",
        ball: "p",
        egg_type: "",
        egg_received_date: "",
        egg_hatched_date: "",
        postcard_received_date: "",
        trade_date: "2019-03-12",
        caught_date: "2019-02-28",
        event: "",
    },
    {
        candy_group: "",
        pokedex_no: "20",
        lucky: false,
        shiny: false,
        shadow: false,
        purified: true,
        region: "",
        costume: "",
        weight: "19.75",
        height: "0.78",
        knows_attack: "",
        meet: "g",
        ball: "pr",
        egg_type: "",
        egg_received_date: "",
        egg_hatched_date: "",
        postcard_received_date: "",
        trade_date: "",
        caught_date: "2019-09-30",
        event: "",
    },
    {
        candy_group: "",
        pokedex_no: "19",
        lucky: false,
        shiny: false,
        shadow: false,
        purified: false,
        region: "",
        costume: "",
        weight: "2.79",
        height: "0.28",
        knows_attack: "",
        meet: "w",
        ball: "p",
        egg_type: "",
        egg_received_date: "",
        egg_hatched_date: "",
        postcard_received_date: "",
        trade_date: "2020-07-26",
        caught_date: "2020-07-26",
        event: "",
    },
    {
        candy_group: "고오스",
        pokedex_no: "94",
        lucky: false,
        shiny: true,
        shadow: false,
        purified: false,
        region: "",
        costume: "",
        weight: "45.43",
        height: "1.51",
        knows_attack: "핥기",
        meet: "r",
        ball: "pr",
        egg_type: "",
        egg_received_date: "",
        egg_hatched_date: "",
        postcard_received_date: "",
        trade_date: "",
        caught_date: "2018-11-03",
        event: "",
    },
    {
        candy_group: "스컹뿡",
        pokedex_no: "434",
        lucky: false,
        shiny: false,
        shadow: true,
        purified: false,
        region: "",
        costume: "",
        weight: "18.07",
        height: "0.41",
        knows_attack: "",
        meet: "g",
        ball: "pr",
        egg_type: "",
        egg_received_date: "",
        egg_hatched_date: "",
        postcard_received_date: "",
        trade_date: "",
        caught_date: "2020-09-10",
        event: "",
    },
];
