var perfect_pokemons = [
    {
        candy_group: "이상해씨",
        pokedex_no: "1",
        lucky: false,
        shiny: false,
        shadow: false,
        purified: false,
        region: "",
        weight: "5.66",
        height: "0.74",
        knows_attack: "",
        meet: "w",
        ball: "p",
        egg_type: "",
        egg_received_date: "",
        egg_hatched_date: "",
        postcard_received_date: "",
        trade_date: "",
        caught_date: "2020-11-15",
        event: "",
    },
    {
        candy_group: "",
        pokedex_no: "3",
        lucky: true,
        shiny: false,
        shadow: false,
        purified: false,
        region: "",
        weight: "88.1",
        height: "1.97",
        knows_attack: "하드플랜트",
        meet: "w",
        ball: "p",
        egg_type: "",
        egg_received_date: "",
        egg_hatched_date: "",
        postcard_received_date: "",
        trade_date: "2020-01-22",
        caught_date: "2020-01-17",
        event: "",
    },
    {
        candy_group: "",
        pokedex_no: "3",
        lucky: false,
        shiny: false,
        shadow: false,
        purified: false,
        region: "",
        weight: "102.15",
        height: "2.04",
        knows_attack: "",
        meet: "w",
        ball: "h",
        egg_type: "",
        egg_received_date: "",
        egg_hatched_date: "",
        postcard_received_date: "",
        trade_date: "",
        caught_date: "2017-02-16",
        event: "",
    },
];
